# Generated by Django 4.2.2 on 2023-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_roomsize_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsize',
            name='room_size',
            field=models.CharField(max_length=10),
        ),
    ]
